# Generated by Django 6.0.3 on 2026-05-22 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlitchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Никнейм')),
                ('belief_level', models.IntegerField(default=50, verbose_name='Уровень веры в матрицу')),
                ('bio', models.TextField(blank=True, verbose_name='Био')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='glitch_profile', to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
