# Generated by Django 5.2.6 on 2026-04-03 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0003_alter_anomaly_options_alter_glitchprofile_options_and_more'),
        ('theories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theory',
            options={'verbose_name': 'Теория', 'verbose_name_plural': 'Теории'},
        ),
        migrations.AlterField(
            model_name='theory',
            name='anomaly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theories', to='anomalies.anomaly', verbose_name='Аномалия'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='explanation',
            field=models.TextField(verbose_name='Объяснение'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Голоса'),
        ),
    ]
