# Generated by Django 5.2.6 on 2026-03-05 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_link', models.URLField()),
                ('verified', models.BooleanField(default=False)),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theories.theory')),
            ],
        ),
    ]
