# Generated by Django 6.0.3 on 2026-05-22 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0001_initial'),
        ('theories', '0003_alter_theory_author_alter_theory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proof',
            options={'verbose_name': 'Доказательство', 'verbose_name_plural': 'Доказательства'},
        ),
        migrations.AlterField(
            model_name='proof',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='evidence_link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='theory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theories.theory', verbose_name='Теория'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Подтверждено или нет'),
        ),
    ]
