# Generated by Django 5.2.6 on 2026-03-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomaly',
            old_name='confirmed',
            new_name='resolved',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='date_observed',
        ),
        migrations.AddField(
            model_name='anomaly',
            name='danger_level',
            field=models.CharField(default='low', max_length=50),
            preserve_default=False,
        ),
    ]
