# Generated by Django 5.2.6 on 2026-04-03 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0002_rename_confirmed_anomaly_resolved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomaly',
            options={'verbose_name': 'Аномалия', 'verbose_name_plural': 'Аномалии'},
        ),
        migrations.AlterModelOptions(
            name='glitchprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='danger_level',
            field=models.CharField(max_length=50, verbose_name='Уровень опасности'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='Решено или нет'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='glitchprofile',
            name='belief_level',
            field=models.IntegerField(default=50, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='glitchprofile',
            name='bio',
            field=models.TextField(verbose_name='Био'),
        ),
        migrations.AlterField(
            model_name='glitchprofile',
            name='nickname',
            field=models.CharField(max_length=100, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='glitchprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль'),
        ),
    ]
