# Generated by Django 6.0.3 on 2026-04-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0004_alter_anomaly_author_alter_anomaly_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='image_path',
            field=models.CharField(blank=True, help_text='Например: "img/anomalies/glitch.jpg"', max_length=255, verbose_name='Путь к картинке'),
        ),
    ]
